Document: linux-gpib-user
Title: Debian linux-gpib-user Manual
Author: <insert document author here>
Abstract: This manual describes what linux-gpib-user is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/linux-gpib-user/linux-gpib-user.sgml.gz

Format: postscript
Files: /usr/share/doc/linux-gpib-user/linux-gpib-user.ps.gz

Format: text
Files: /usr/share/doc/linux-gpib-user/linux-gpib-user.text.gz

Format: HTML
Index: /usr/share/doc/linux-gpib-user/html/index.html
Files: /usr/share/doc/linux-gpib-user/html/*.html
