#!/bin/sh
set -e
# Automatically added by dh_installmodules/11.3.2ubuntu1
if [ -e /boot/System.map-4.18.0-11-generic ]; then
	depmod -a -F /boot/System.map-4.18.0-11-generic 4.18.0-11-generic || true
fi
# End automatically added section
