Document: linux-gpib-kernel
Title: Debian linux-gpib-kernel Manual
Author: <insert document author here>
Abstract: This manual describes what linux-gpib-kernel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/linux-gpib-kernel/linux-gpib-kernel.sgml.gz

Format: postscript
Files: /usr/share/doc/linux-gpib-kernel/linux-gpib-kernel.ps.gz

Format: text
Files: /usr/share/doc/linux-gpib-kernel/linux-gpib-kernel.text.gz

Format: HTML
Index: /usr/share/doc/linux-gpib-kernel/html/index.html
Files: /usr/share/doc/linux-gpib-kernel/html/*.html
